<GameOverPopup>:
    orientation: 'vertical'
    size_hint : None, None
    size : dp(420), dp(260)
    winner_text: 'Winner'

    BoxLayout:
        orientation: 'vertical'
        padding: dp(18)
        spacing: dp(16)
        Label:
            text: root.winner_text
            font_size: dp(24)
        Label:
            font_size: dp(24)
            text: root.reason

<ClockWidget>:
    orientation: 'vertical'
    padding: dp(16)

    Label: 
        text: "White: " + root.white_text
        font_size: 32
        halign: 'left'
        valign: 'bottom'
    
    Label: 
        text: "Black: " + root.black_text
        font_size: 32
        halign: 'left'
        valign: 'top'



<Cell>:
    background_normal: ''
    background_down: ''
    background_disabled_normal: ''   
    background_disabled_down: ''    
    border: 0,0,0,0   

<BoardView>:
    name: 'Board'
    orientation: "vertical"
    padding: dp(16)
    spacing: dp(12)
        
    FloatLayout:
        BoxLayout:
            orientation: "vertical"
            padding: dp(16)
            spacing: dp(12)

            size_hint: 1, 0.1
            Button:
                background_color: (0,0,0)
                size_hint: None, None
                size: dp(100), dp(40)
                text: "Menu"
                pos_hint: {"center_x":0.5, "center_y": 1}
                on_release: 
                    app.root.current = 'Menu'
                    root.manager.transition.direction = 'down'

        RecycleView:
            id: rv
            viewclass: "Cell"
            data: []
            size_hint: None, None      
            do_scroll_x: False
            do_scroll_y: False
            bar_width: 0
            pos_hint: {"center_x": .5, "center_y": 0.5}

            RecycleGridLayout:
                cols: 10
                default_size: dp(56), dp(56)  
                default_size_hint: None, None
                size_hint: None, None
                width: self.minimum_width
                height: self.minimum_height
                spacing: dp(2)

        ClockWidget:
            pos_hint: {'center_x':0.1, 'center_y': 0.5}
            size_hint: 0.2,0.8


<SetupScreen>:
    name: 'Setup'
    FloatLayout:
        size_hint: 1,1
        Button:
            pos_hint: {"center_x": 0.75, "center_y": 0.25}
            text: "Difficulty"
            font_size: 32
            size_hint: 0.2,0.08
            on_release: 
                root.DifficultyDropdown.open(self)
    
        Button:
            pos_hint: {"center_x": 0.25, "center_y": 0.75}
            text: "White Player"
            font_size: 32
            size_hint: 0.2,0.08
            on_release: 
                root.white_drop_down.open(self)
        Button:
            pos_hint: {"center_x": 0.75, "center_y": 0.75}
            text: "Black Player"
            font_size: 32
            size_hint: 0.2,0.08
            on_release: 
                root.black_drop_down.open(self)
        Button:
            pos_hint: {"center_x": 0.25, "center_y": 0.25}
            text: "Start Game"
            font_size: 32
            size_hint: 0.2,0.08
            on_release: 
                app.start_move()
                app.root.current = 'Board'
                root.manager.transition.direction = 'up'



<MenuScreen>:
    name: 'Menu'
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height
        Label:
            pos_hint: {"center_x": 0.5, "center_y": 0.7}
            text: 'Katarenga'
            font_size: 50
        FloatLayout:
            size_hint: 1,1
            FloatLayout:
                size_hint: 1,1
                pos_hint: {"center_x": 0.5, "center_y": 0.7}
                Button:
                    pos_hint: {"center_x": 0.25, "center_y": 1}
                    text: "NEW GAME"
                    font_size: 32
                    size_hint: 0.2,0.15
                    on_release: 
                        app.new_game()
                        app.root.current = 'Setup'
                        root.manager.transition.direction = 'up'
                Button:
                    pos_hint: {"center_x": .75, "center_y": 1}
                    text: "Load Game"
                    font_size: 32
                    size_hint: 0.2,0.15
                    on_release: 
                        app.load_game()
                        app.root.current = 'Board'
                        root.manager.transition.direction = 'up'
                Button:
                    pos_hint: {"center_x": 0.5, "center_y": 0.4}
                    text: "Save Game"
                    font_size: 32
                    size_hint: 0.2,0.15
                    on_release: 
                        app.save_game()
        

                    

            
            



WindowManager:
    MenuScreen:
    BoardView:
    SetupScreen: